#set(_EVENT2_EVENT_COMPAT_H_ yes)
#set(_EVENT2_EVENT_CONFIG_H_ yes)
#set(_EVENT2_EVENT_H_ yes)
#set(_EVENT2_EVENT_KEYVALQ_STRUCT_H_ yes)
#set(_EVENT2_EVENT_STRUCT_H_ yes)
#set(_EVENT_ yes)
#set(_EVENT_CONFIG_H_ yes)
#set(_EVENT_DEFINED_TQENTRY yes)
#set(_EVENT_DEFINED_TQHEAD yes)
#set(_EVENT_DISABLE_THREAD_SUPPORT yes)
#set(_EVENT_DNS_USE_CPU_CLOCK_FOR_ID yes)
#set(_EVENT_DNS_USE_FTIME_FOR_ID yes)
#set(_EVENT_DNS_USE_GETTIMEOFDAY_FOR_ID yes)
#set(_EVENT_ERR_ABORT yes)
#set(_EVENT_HT_H yes)
#set(_EVENT_H_ yes)
#set(_EVENT_INTERNAL_H_ yes)
#set(_EVENT_IN_DOXYGEN yes)
#set(_EVENT_IOCP_INTERNAL_H yes)
#set(_EVENT_IPV6_INTERNAL_H yes)
#set(_EVENT_LOG_* yes)
#set(_EVENT_LOG_DEBUG yes)
#set(_EVENT_LOG_ERR yes)
#set(_EVENT_LOG_MSG yes)
#set(_EVENT_LOG_WARN yes)
#set(_EVENT_MM_INTERNAL_H yes)
#set(_EVENT_NUMERIC_VERSION yes)
#set(_EVENT_PACKAGE yes)
#set(_EVENT_PACKAGE_BUGREPORT yes)
#set(_EVENT_PACKAGE_NAME yes)
#set(_EVENT_PACKAGE_STRING yes)
#set(_EVENT_PACKAGE_TARNAME yes)
#set(_EVENT_PACKAGE_VERSION yes)
#set(_EVENT_PTHREAD_CREATE_JOINABLE yes)
#set(_EVENT_SSIZE_t yes)
#set(_EVENT_STDC_HEADERS yes)
#set(_EVENT_TIME_WITH_SYS_TIME yes)
#set(_EVENT_UTIL_INTERNAL_H yes)
#set(_EVENT_VERSION yes)
#set(_EVENT___cplusplus yes)
#set(_EVENT___func__ yes)
#set(_EVENT_const yes)
#set(_EVENT_inline yes)
#set(_EVENT_pid_t yes)
#set(_EVENT_size_t yes)
#set(_EVENT_socklen_t yes)
#set(_EVENT_ssize_t yes)

#
# Modules
#
include(CheckFunctionExists)
include(CheckIncludeFiles)
include(CheckSymbolExists)
include(CheckStructHasMember)
include(CheckTypeSize)

#
# Environment for checks
#

check_include_files(netdb.h _EVENT_HAVE_NETDB_H)
check_include_files(netinet/in.h _EVENT_HAVE_NETINET_IN_H)
check_include_files(netinet/in6.h _EVENT_HAVE_NETINET_IN6_H)
check_include_files(sys/socket.h _EVENT_HAVE_SYS_SOCKET_H)

if(_EVENT_HAVE_NETINET_IN_H)
	list(APPEND CMAKE_EXTRA_INCLUDE_FILES "netinet/in.h")
endif(_EVENT_HAVE_NETINET_IN_H)

if(_EVENT_HAVE_NETINET_IN6_H)
	list(APPEND CMAKE_EXTRA_INCLUDE_FILES "netinet/in6.h")
endif(_EVENT_HAVE_NETINET_IN6_H)

if(_EVENT_HAVE_SYS_SOCKET_H)
	list(APPEND CMAKE_EXTRA_INCLUDE_FILES "sys/socket.h")
endif(_EVENT_HAVE_SYS_SOCKET_H)

if(_EVENT_HAVE_NETDB_H)
	list(APPEND CMAKE_EXTRA_INCLUDE_FILES "netdb.h")
endif(_EVENT_HAVE_NETDB_H)

if(WIN32)
	list(APPEND CMAKE_REQUIRED_DEFINITIONS "-DWIN32_WINNT=0x400")
	list(APPEND CMAKE_REQUIRED_DEFINITIONS "-D_WIN32_WINNT=0x400")
	list(APPEND CMAKE_REQUIRED_DEFINITIONS "-DWIN32_LEAN_AND_MEAN")
	list(APPEND CMAKE_EXTRA_INCLUDE_FILES "winsock2.h")
	list(APPEND CMAKE_EXTRA_INCLUDE_FILES "ws2tcpip.h")
endif(WIN32)


option(_EVENT_DISABLE_DEBUG_MODE "build without support for debug mode" no)
option(_EVENT_DISABLE_MM_REPLACEMENT "do not allow replacing the mm functions" no)
option(_EVENT_DISABLE_THREAD_SUPPORT "not compiled with thread support" no)

check_include_files(unistd.h _EVENT_HAVE_UNISTD_H)
check_function_exists(arc4random _EVENT_HAVE_ARC4RANDOM)
check_function_exists(arc4random_buf _EVENT_HAVE_ARC4RANDOM_BUF)
check_include_files(arpa/inet.h _EVENT_HAVE_ARPA_INET_H)
check_function_exists(clock_gettime _EVENT_HAVE_CLOCK_GETTIME)
check_symbol_exists(CTL_KERN "sys/types.h;sys/sysctl.h" _EVENT_HAVE_DECL_CTL_KERN)
check_symbol_exists(KERN_ARND "sys/types.h;sys/sysctl.h" _EVENT_HAVE_DECL_KERN_ARND)
check_symbol_exists(KERN_RANDOM "sys/types.h;sys/sysctl.h" _EVENT_HAVE_DECL_KERN_RANDOM)
check_symbol_exists(RANDOM_UUID "sys/types.h;sys/sysctl.h" _EVENT_HAVE_DECL_RANDOM_UUID)
check_include_files(sys/devpoll.h _EVENT_HAVE_SYS_DEVPOLL_H)
set(_EVENT_HAVE_DEVPOLL ${_EVENT_HAVE_SYS_DEVPOLL_H})
check_include_files(dlfcn.h _EVENT_HAVE_DLFCN_H)
check_function_exists(epoll_ctl _EVENT_HAVE_EPOLL_CTL)
set(_EVENT_HAVE_EPOLL ${_EVENT_HAVE_EPOLL_CTL})
check_function_exists(eventfd _EVENT_HAVE_EVENTFD)
check_function_exists(port_create _EVENT_HAVE_EVENT_PORTS)
check_function_exists(fcntl _EVENT_HAVE_FCNTL)
check_include_files(fcntl.h _EVENT_HAVE_FCNTL_H)
check_type_size(fd_mask _EVENT_HAVE_FD_MASK)
check_function_exists(getaddrinfo _EVENT_HAVE_GETADDRINFO)
check_function_exists(getegid _EVENT_HAVE_GETEGID)
check_function_exists(geteuid _EVENT_HAVE_GETEUID)
#check_function_exists(gethostbyname_r _EVENT_HAVE_GETHOSTBYNAME_R)
#check_function_exists(gethostbyname_r_3_arg _EVENT_HAVE_GETHOSTBYNAME_R_3_ARG)
#check_function_exists(gethostbyname_r_5_arg _EVENT_HAVE_GETHOSTBYNAME_R_5_ARG)
#check_function_exists(gethostbyname_r_6_arg _EVENT_HAVE_GETHOSTBYNAME_R_6_ARG)
set(_EVENT_HAVE_GETHOSTBYNAME_R)
set(_EVENT_HAVE_GETHOSTBYNAME_R_3_ARG)
set(_EVENT_HAVE_GETHOSTBYNAME_R_5_ARG)
set(_EVENT_HAVE_GETHOSTBYNAME_R_6_ARG)
check_function_exists(getnameinfo _EVENT_HAVE_GETNAMEINFO)
check_function_exists(getprotobynumber _EVENT_HAVE_GETPROTOBYNUMBER)
check_function_exists(getservbyname _EVENT_HAVE_GETSERVBYNAME)
check_function_exists(gettimeofday _EVENT_HAVE_GETTIMEOFDAY)
check_function_exists(inet_aton _EVENT_HAVE_INET_ATON)
check_function_exists(inet_ntop _EVENT_HAVE_INET_NTOP)
check_function_exists(inet_pton _EVENT_HAVE_INET_PTON)
check_include_files(inttypes.h _EVENT_HAVE_INTTYPES_H)
check_function_exists(issetugid _EVENT_HAVE_ISSETUGID)
check_function_exists(kqueue _EVENT_HAVE_KQUEUE)
check_include_files(memory.h _EVENT_HAVE_MEMORY_H)
check_function_exists(mmap _EVENT_HAVE_MMAP)
check_include_files(openssl/bio.h _EVENT_HAVE_OPENSSL_BIO_H)
check_function_exists(pipe _EVENT_HAVE_PIPE)
check_function_exists(poll _EVENT_HAVE_POLL)
check_include_files(poll.h _EVENT_HAVE_POLL_H)
check_function_exists(port_create _EVENT_HAVE_PORT_CREATE)
check_include_files(port.h _EVENT_HAVE_PORT_H)
check_function_exists(putenv _EVENT_HAVE_PUTENV)
check_type_size("sa_family_t" _EVENT_HAVE_SA_FAMILY_T)
check_function_exists(select _EVENT_HAVE_SELECT)
check_function_exists(sendfile _EVENT_HAVE_SENDFILE)
check_function_exists(setenv _EVENT_HAVE_SETENV)
check_symbol_exists(F_SETFD fcntl.h _EVENT_HAVE_SETFD)
check_function_exists(sigaction _EVENT_HAVE_SIGACTION)
check_function_exists(signal _EVENT_HAVE_SIGNAL)
check_function_exists(splice _EVENT_HAVE_SPLICE)
check_include_files(stdarg.h _EVENT_HAVE_STDARG_H)
check_include_files(stddef.h _EVENT_HAVE_STDDEF_H)
check_include_files(stdint.h _EVENT_HAVE_STDINT_H)
check_include_files(stdlib.h _EVENT_HAVE_STDLIB_H)
check_include_files(strings.h _EVENT_HAVE_STRINGS_H)
check_include_files(string.h _EVENT_HAVE_STRING_H)
check_function_exists(strlcpy _EVENT_HAVE_STRLCPY)
check_function_exists(strsep _EVENT_HAVE_STRSEP)
check_function_exists(strtok_r _EVENT_HAVE_STRTOK_R)
check_function_exists(strtoll _EVENT_HAVE_STRTOLL)
check_type_size("struct addrinfo" _EVENT_HAVE_STRUCT_ADDRINFO)
check_type_size("struct in6_addr" _EVENT_HAVE_STRUCT_IN6_ADDR)
check_struct_has_member("struct in6_addr" s6_addr16 netinet/in.h _EVENT_HAVE_STRUCT_IN6_ADDR_S6_ADDR16)
check_struct_has_member("struct in6_addr" s6_addr32 netinet/in.h _EVENT_HAVE_STRUCT_IN6_ADDR_S6_ADDR32)
check_type_size("struct sockaddr_in6" _EVENT_HAVE_STRUCT_SOCKADDR_IN6)
check_struct_has_member("struct sockaddr_in6" sin6_len netinet/in.h _EVENT_HAVE_STRUCT_SOCKADDR_IN6_SIN6_LEN)
check_struct_has_member("struct sockaddr_in" sin_len netinet/in.h _EVENT_HAVE_STRUCT_SOCKADDR_IN_SIN_LEN)
check_type_size("struct sockaddr_storage" _EVENT_HAVE_STRUCT_SOCKADDR_STORAGE)
check_struct_has_member("struct sockaddr_storage" ss_family netinet/in.h _EVENT_HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY)
check_struct_has_member("struct sockaddr_storage" __ss_family netinet/in.h _EVENT_HAVE_STRUCT_SOCKADDR_STORAGE___SS_FAMILY)
check_function_exists(sysctl _EVENT_HAVE_SYSCTL)
check_include_files(sys/epoll.h _EVENT_HAVE_SYS_EPOLL_H)
check_include_files(sys/eventfd.h _EVENT_HAVE_SYS_EVENTFD_H)
check_include_files(sys/event.h _EVENT_HAVE_SYS_EVENT_H)
check_include_files(sys/ioctl.h _EVENT_HAVE_SYS_IOCTL_H)
check_include_files(sys/mman.h _EVENT_HAVE_SYS_MMAN_H)
check_include_files(sys/param.h _EVENT_HAVE_SYS_PARAM_H)
check_include_files(sys/queue.h _EVENT_HAVE_SYS_QUEUE_H)
check_include_files(sys/select.h _EVENT_HAVE_SYS_SELECT_H)
check_include_files(sys/sendfile.h _EVENT_HAVE_SYS_SENDFILE_H)
check_include_files(sys/stat.h _EVENT_HAVE_SYS_STAT_H)
check_include_files(sys/sysctl.h _EVENT_HAVE_SYS_SYSCTL_H)
check_include_files(sys/time.h _EVENT_HAVE_SYS_TIME_H)
check_include_files(sys/types.h _EVENT_HAVE_SYS_TYPES_H)
check_include_files(sys/uio.h _EVENT_HAVE_SYS_UIO_H)
check_include_files(sys/wait.h _EVENT_HAVE_SYS_WAIT_H)
check_symbol_exists(TAILQ_FOREACH sys/queue.h _EVENT_HAVE_TAILQFOREACH)
check_symbol_exists(TIMERADD sys/time.h _EVENT_HAVE_TIMERADD)
check_symbol_exists(TIMERCLEAR sys/time.h _EVENT_HAVE_TIMERCLEAR)
check_symbol_exists(TIMERCMP sys/time.h _EVENT_HAVE_TIMERCMP)
check_type_size(uint16_t _EVENT_HAVE_UINT16_T)
check_type_size(uint32_t _EVENT_HAVE_UINT32_T)
check_type_size(uint64_t _EVENT_HAVE_UINT64_T)
check_type_size(uint8_t _EVENT_HAVE_UINT8_T)
check_type_size(uintptr_t _EVENT_HAVE_UINTPTR_T)
check_function_exists(umask _EVENT_HAVE_UMASK)
check_function_exists(unsetenv _EVENT_HAVE_UNSETENV)
check_function_exists(vasprintf _EVENT_HAVE_VASPRINTF)

set(_EVENT_HAVE_WORKING_KQUEUE ${_EVENT_HAVE_WORKING_KQUEUE}) # TODO

check_include_files(zlib.h _EVENT_HAVE_ZLIB_H)

set(_EVENT_LT_OBJDIR ".libs/")
set(_EVENT_NO_MINUS_C_MINUS_O)
set(_EVENT_PACKAGE "libevent")
set(_EVENT_PACKAGE_BUGREPORT "")
set(_EVENT_PACKAGE_NAME "")
set(_EVENT_PACKAGE_STRING "")
set(_EVENT_PACKAGE_TARNAME "")
set(_EVENT_PACKAGE_URL "")
set(_EVENT_PACKAGE_VERSION "")
set(_EVENT_PTHREAD_CREATE_JOINABLE) # XXX
check_type_size(int _EVENT_SIZEOF_INT)
check_type_size(long _EVENT_SIZEOF_LONG)
check_type_size("long long" _EVENT_SIZEOF_LONG_LONG)
check_type_size(pthread_t _EVENT_SIZEOF_PTHREAD_T)
check_type_size(short _EVENT_SIZEOF_SHORT)
check_type_size(size_t _EVENT_SIZEOF_SIZE_T)
check_type_size("void *" _EVENT_SIZEOF_VOID_P)
set(_EVENT_STDC_HEADERS 1)
set(_EVENT_TIME_WITH_SYS_TIME 1)
set(_EVENT___func__)
set(_EVENT_const)

